---
title: "README"
author: "Erik Rehnberg"
date: "6/25/2020"
output: html_document
---

## gofarR

The goal of this package will be to take as inputs both direct calls to the Peloton API and the workouts summary that can be directly downloaded from a user's profile page and analyze your workout data along several metrics.

### Currently working functions
* top_instructor() -  Shows top instructor, both overall and for each discipline; defaults to all

### Currently planned function/abilities
#### From \<username>_workouts.csv
* Breakdown of Live Classes, On-Demand Classes, and Just Ride workouts
* Summarize and plot average power output by class duration (defaults to ignore Scenic rides, can include them)
* Summarize and plot average power output by Just Ride duration
* Plot histogram of preferred times to workout (overall and by discipline)

#### From API
* Decoupling (Pwr:Hr first/second half of classs ratios) by class duration


The package currently uses a number of functions from bweiher's pelotonR package, which is, as of this version's release, only available on GitHub at https://github.com/bweiher/pelotonR. As a result, the functions have been directly duplicated here. If the pelotonR package is uploaded to CRAN, I will adjust this pacakge in order to call those functions from the dedicated package.
